
package gui_ta_muhedi;
import static java.time.Clock.system;
import java.util.Scanner;
        

public class MUHEDI extends javax.swing.JFrame {

    /**
     * Creates new form MUHEDI
     */
    public MUHEDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JUDUL = new javax.swing.JLabel();
        PER2 = new javax.swing.JLabel();
        PER3 = new javax.swing.JLabel();
        HASILBUTTON = new javax.swing.JButton();
        sebelahhasil = new javax.swing.JButton();
        HASIL = new javax.swing.JTextField();
        Masukan1 = new javax.swing.JTextField();
        masukan2 = new javax.swing.JTextField();
        pilihan3 = new javax.swing.JComboBox<>();
        PER1 = new javax.swing.JLabel();
        hasilku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JUDUL.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        JUDUL.setText("KLO JAWABANNYA SESUAI, HEBAT!");
        getContentPane().add(JUDUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 440, 40));

        PER2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        PER2.setText("SAYA BARANG PERUSAKMU, CARI ARTI LAIN!");
        getContentPane().add(PER2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 320, 40));

        PER3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        PER3.setText("lanjut?  ( 1.IYA  2.RESET 3. KELUAR ) ");
        getContentPane().add(PER3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        HASILBUTTON.setText("HASIL");
        HASILBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HASILBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(HASILBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 30));

        sebelahhasil.setText("PILIHAN 1,2 OR 3");
        sebelahhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebelahhasilActionPerformed(evt);
            }
        });
        getContentPane().add(sebelahhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 250, 130, 30));

        HASIL.setBackground(new java.awt.Color(204, 0, 0));
        HASIL.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        HASIL.setForeground(new java.awt.Color(255, 255, 0));
        HASIL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HASIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HASILActionPerformed(evt);
            }
        });
        getContentPane().add(HASIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 250, 40));

        Masukan1.setBackground(new java.awt.Color(240, 240, 240));
        Masukan1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Masukan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masukan1ActionPerformed(evt);
            }
        });
        getContentPane().add(Masukan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, 30));

        masukan2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        masukan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukan2ActionPerformed(evt);
            }
        });
        getContentPane().add(masukan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 120, 40));

        pilihan3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. IYA", "2. RESET", "3. TUTUP", " " }));
        pilihan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan3ActionPerformed(evt);
            }
        });
        getContentPane().add(pilihan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 100, 30));

        PER1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        PER1.setText("\"U . T . . . U\" Apa itu??");
        getContentPane().add(PER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 30));

        hasilku.setBackground(new java.awt.Color(255, 255, 153));
        hasilku.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        hasilku.setForeground(new java.awt.Color(255, 0, 0));
        hasilku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilkuActionPerformed(evt);
            }
        });
        getContentPane().add(hasilku, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 250, 40));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_ta_muhedi/Background-Banner-1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HASILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HASILActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_HASILActionPerformed

    private void Masukan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masukan1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_Masukan1ActionPerformed

    private void masukan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukan2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_masukan2ActionPerformed

    private void HASILBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HASILBUTTONActionPerformed
   String isi1=Masukan1.getText();
   String isi2=masukan2.getText(); 
  HASIL.setText("1.  "+isi1+ " 2. "+isi2);
  
  GUI_TA_MUHEDI newhasil = new GUI_TA_MUHEDI();
  newhasil.sethasil2("1.UNTUKMU & 2.SAYANGKU");
       hasilku.setText("benarnya : " + newhasil.gethasil2());
    }//GEN-LAST:event_HASILBUTTONActionPerformed

    private void pilihan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan3ActionPerformed
      
    }//GEN-LAST:event_pilihan3ActionPerformed

    private void sebelahhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebelahhasilActionPerformed
        int isi3 = pilihan3.getSelectedIndex();
        switch (isi3){
            case(0):
                HASIL.setText("Lanjut");
                break;
        
            case (1):
                Masukan1.setText("");
                masukan2.setText(""); 
                HASIL.setText(""); 
                hasilku.setText(""); 
                break;
            
            case (2):
                dispose();
                break;
        }
       // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_sebelahhasilActionPerformed

    private void hasilkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MUHEDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MUHEDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MUHEDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MUHEDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MUHEDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HASIL;
    private javax.swing.JButton HASILBUTTON;
    private javax.swing.JLabel JUDUL;
    private javax.swing.JTextField Masukan1;
    private javax.swing.JLabel PER1;
    private javax.swing.JLabel PER2;
    private javax.swing.JLabel PER3;
    private javax.swing.JTextField hasilku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField masukan2;
    private javax.swing.JComboBox<String> pilihan3;
    private javax.swing.JButton sebelahhasil;
    // End of variables declaration//GEN-END:variables

    private void popup() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
